name: 💡 Feature Request
description: Suggest any ideas
title: "[FEATURE] <title>"
labels: ["Feature"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing idea or feature request for this?
    description: Pease search to see if a feature request has already been submitted.
    options:
    - label: I have searched the existing feature requests.
      required: true
- type: textarea
  attributes:
    label: Describe the feature request you'd like.
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request.
  validations:
    required: false