name: 'Publish NuGet Package'
author: 'Sleepy Star Farm'
description: 'Build and Publish NuGet Package.'

inputs:
  REGISTRY:
    description: 'Optional package source for which to set up authentication. Default is `https://api.nuget.org/v3/index.json`.'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  SOLUTION:
    description: 'Optional path to a *.sln file. Default is ``.'
    required: false
    default: ''
  PROJECT_DIRECTORY:
    description: 'The path to the project directory containing the .csproj file. Default is `.`.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: Sleepy-Star-Farm/.github/actions/dotnet/test@dev
      with:
        REGISTRY: ${{ inputs.REGISTRY }}
        SOLUTION: ${{ inputs.SOLUTION }}
    - name: Pack NuGet Package...
      run: dotnet pack --configuration Release ${{ inputs.PROJECT_DIRECTORY }}/*.csproj
      shell: bash
    - name: Publish NuGet Package...
      run: dotnet nuget push ${{ inputs.PROJECT_DIRECTORY }}/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source ${{ inputs.REGISTRY }} --skip-duplicate
      shell: bash