name: 'Setup Node Environment'
author: 'Sleepy Star Farm'
description: 'Custom Node Setup Workflow'

inputs:
  NODE_VERSION:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    required: false
    default: 'lts/*'
  REGISTRY:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    required: false
    default: ''
  SCOPE:
    description: 'Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).'
    required: false
    default: ''
  TOKEN:
    description: Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

runs:
  using: 'composite'
  steps:
    - uses: Sleepy-Star-Farm/.github/actions/checkout@dev
    - name: Set up Node Environment...
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: ${{ inputs.REGISTRY_URL }}
        scope: ${{ inputs.SCOPE }}
        token: ${{ inputs.TOKEN }}
