name: 'Docker Login'
author: 'Sleepy Star Farm'
description: 'Custom Docker Login Workflow'

inputs:
  REGISTRY:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: true
  USERNAME:
    description: 'Username used to log against the Docker registry'
    required: true
  PASSWORD:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: Sleepy-Star-Farm/.github/actions/docker/setup@dev
    - name: Logging into Docker Registry...
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}